### PR TITLE
enhance: Added published recorded sessions

### PR DESCRIPTION
**Pull request by karinchechik**
Hi,

5 recorded talks were published. I added links to the video with the relevant time.

### CODE REVIEW

**Comment by GoudekettingRM** [comment]
Are these publicly available? I see that youtube calls them 'hidden', so I'm not sure we're allowed to just share them like this. Where did you find them? I don't want to rub Frontend Love and Vue Global the wrong way 😅

**Comment by karinchechik** [comment]
🤔
It's actually on Frontend Love's official youtube, but I think I got the link in one of their emails.
I didn't pay for full access to the videos, so it is not something they charge for.
I'm not sure why it's 'hidden' to be honest.

**Comment by karinchechik** [comment]
@GoudekettingRM They published it on Linkedin too 😊 
You can see it [here](https://www.linkedin.com/posts/frontendlove_premiere-of-our-editor-picked-top-5-talks-activity-6768853372477956096-i7Cu)

**Comment by GoudekettingRM** [comment]
Oh cool! It's the top 5 talks, nice! In with this thing then!

**Pull request merged**
